---
title: "Assignment 4"
author: "Shellby Johnson"
date: "November 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(kableExtra)
library(knitr)
library(vcdExtra)
library(dplyr)
library(car)
library(onewaytests)


lobster_size <- read_csv("lobster_size_abundance.csv") #frequency version of lobster size data
trap_counts <- read_csv("lobster_traps.csv")

#expanded lobster size data
lobster_tidy <- expand.dft(data.frame(lobster_size), freq = "COUNT")
```


```{r, message=FALSE}

#1. 
#total # of lobsters sampled at each site each year
totalcount_year <- lobster_size %>% 
  group_by(YEAR, SITE) %>% 
  summarize(total = sum(COUNT))

kable(totalcount_year)

#lobster abundance
size_column <- ggplot(totalcount_year, aes(x = YEAR, y = total))+
  geom_line(size = 2, aes(colour = SITE)) +
  geom_point(size = 3)+
  labs(y = "Total Number of Spiny Lobster", x = "Sampling Year")+
  ggtitle("California Spiny Lobster Totals for 5 LTER Sites (2012-2017)")+
  theme_classic()

size_column

#total # of traps at each site each year- 9 sites(8 sites with in between sites values removed)
totalcount_traps <- trap_counts %>%
  filter(SITE != "AHND to AQUE", SITE != "ABUR", SITE != "AHND", SITE != "GOLB") %>% 
  group_by(YEAR, SITE) %>% 
  summarize(total = sum(TRAPS))

#traps line plots
traps_column <- ggplot(totalcount_traps, aes(x = YEAR, y = total))+
  geom_line(size = 2, aes(colour = SITE))+
  geom_point(size = 3)+
  labs(y = "Total Number of Traps", x = "Sampling Year")+
  ggtitle("Total Number of Commercial Traps at 5 LTER Sites (2012-2017)")+
  theme_classic()


traps_column
```

**Figure 1.** Total counts of California Spiny Lobster at 5 Longterm Ecological Research sites from 2012 to 2017.  

**Figure 2.** Total counts of commercial traps at 5 Longterm Ecological Research sites from 2012 to 2017.

```{r,  message=FALSE, include=FALSE, results='hide'}
#2a. Will do short exploratory data to look at distribution to see if it satisfies assumptions for parametric ANOVA test

lobster_size_hist <- ggplot(lobster_tidy, aes(x = SIZE)) + 
  geom_histogram( bins= 33, aes(fill= SITE))+
  facet_wrap(~ SITE, scale = "free")

lobster_size_hist #exploratory histogram of lobster sizes for all 5 sites

lobster_qqs <-  ggplot(lobster_tidy, aes(sample = SIZE)) +
  geom_qq(aes(color = SITE)) +
  facet_wrap(~ SITE, scale = "free")

lobster_qqs #exploratory qq plots of lobster sizes for all 5 sites

#Distribution looks pretty normal across the sites and qq plots are fairly linear

#Now on to equal variance test

summary_lobster <- lobster_tidy %>% 
  filter(YEAR == "2017") %>% 
  group_by(SITE) %>% 
  summarize(
    mean = mean(SIZE),
    sd = sd(SIZE),
    variance = var(SIZE)
  )
  
  summary_lobster
  
#We are now using levene's test for equal variances
  
lobster_levene <- leveneTest(SIZE ~ SITE, data = lobster_tidy)

lobster_levene

## Largest variance is <4x the smallest (refer to the "summary_lobster" df), so ANOVA can still be used even though levene's test says that they are unequal. 

```


```{r, message=FALSE, include=FALSE, results='hide'}


#So we can use an ANOVA test to compare means across the 5 sites in 2017. However, before we run the test, let's just see how the means look compared to one another >>> boxplot. 


lobster17 <- lobster_tidy %>% 
  filter(YEAR == "2017")
lobster17

box <-  ggplot(lobster17, aes(x = SITE, y = SIZE)) +
  geom_boxplot(width = 0.4) +
  geom_jitter(width = 0.1, alpha = 0.5, aes(color = SITE))

box
```

```{r}

#2b.  ANOVA TEST

#Need to do a test to compare means (lobster size) across all 5 LTER sites in 2017

#Null: Mean lobster sizes across all 5 sites are equal
#Alternative: At least 2 sites have mean lobster sizes that are unequal 



## ANOVA revealed that there is a significant difference in means across the sites and the post-hoc clarified that means differ between 3 pairs of sites (NAPL/IVEE, NAPL/CARP)

aov2 <- aov(SIZE ~ SITE, data = lobster17) #lobster ANOVA

lobster_ph <- TukeyHSD(aov2)

lobster_ph



```




```{r}

#2C. Column graph to show results of ANOVA

lobster_colgraph <- summary_lobster %>% 
  ggplot(aes(x = SITE, y = mean)) +
  geom_col(fill = "red", colour = "black", width = .5 ) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.3) +
  labs(x = "LTER SITE", 
         y = "Mean Lobster Size (carapace length) mm",
         title = "Mean Lobster Size at 5 LTER Sites (2017)") +
  theme_classic()

lobster_colgraph

```

```{r}
#3, Part 1

#Created data frames to use for unpaired t-tests, and created histograms to explore whether the data is normally distributed. Will also do F-tests to check for equal variance


IVEE_12_17<-lobster_tidy %>% 
  select(SITE, YEAR, SIZE) %>% 
  filter(SITE=="IVEE", YEAR=="2012"|YEAR=="2017")
  
IVEE_12_17

IVEE_1217_hist<-ggplot(IVEE_12_17, aes(x=SIZE))+
  geom_histogram()+
  facet_wrap(~YEAR, scale="free")
  
IVEE_1217_hist

F_test_1<-IVEE_12_17 %>% 
  var.test(SIZE~YEAR, data=.)

F_test_1  #p-value=0.307 compare values to make sure it is correct
#####################################################################################

NAPL_12_17<-lobster_tidy %>% 
  select(SITE, YEAR, SIZE) %>% 
  filter(SITE=="NAPL", YEAR=="2012"|YEAR=="2017")
  
NAPL_12_17


NAPL_1217_hist<-ggplot(NAPL_12_17, aes(x=SIZE))+
  geom_histogram()+
  facet_wrap(~YEAR, scale="free")
  
NAPL_1217_hist

F_test_2<-NAPL_12_17 %>% 
  var.test(SIZE~YEAR, data=.)

F_test_2  #p-value=0.7685

######################################################################################

AQUE_12_17<-lobster_tidy %>% 
  select(SITE, YEAR, SIZE) %>% 
  filter(SITE=="AQUE", YEAR=="2012"|YEAR=="2017")

AQUE_12_17


AQUE_1217_hist<-ggplot(AQUE_12_17, aes(x=SIZE))+
  geom_histogram()+
  facet_wrap(~YEAR, scale="free")
  
AQUE_1217_hist

F_test_3<-AQUE_12_17 %>% 
  var.test(SIZE~YEAR, data=.)

F_test_3  #p-value=0.2986

######################################################################################

CARP_12_17<-lobster_tidy %>% 
  select(SITE, YEAR, SIZE) %>% 
  filter(SITE=="CARP", YEAR=="2012"|YEAR=="2017")

CARP_12_17


CARP_1217_hist<-ggplot(CARP_12_17, aes(x=SIZE))+
  geom_histogram()+
  facet_wrap(~YEAR, scale="free")
  
CARP_1217_hist

F_test_4<-CARP_12_17 %>% 
  var.test(SIZE~YEAR, data=.)

F_test_4  #p-value=0.2043

#######################################################################################

MOHK_12_17<-lobster_tidy %>% 
  select(SITE, YEAR, SIZE) %>% 
  filter(SITE=="MOHK", YEAR=="2012"|YEAR=="2017")

MOHK_12_17

MOHK_1217_hist<-ggplot(MOHK_12_17, aes(x=SIZE))+
  geom_histogram()+
  facet_wrap(~YEAR, scale="free")
  
MOHK_1217_hist

F_test_5<-MOHK_12_17 %>% 
  var.test(SIZE~YEAR, data=.)

F_test_5  #p-value=0.1509


#I REACH THE CONCLUSION THAT VARIANCES BETWEEN 2012 & 2017 SAMPLES, AT ALL SITES, ARE EQUAL


```


```{r}
#3, Part 2

#Will do unpaired t-tests to compare lobster sizes between 2012 and 2017 at each of the 5 sites. Did unpaired because there was not a 1-to-1 ratio in data.

ivee_12<-IVEE_12_17 %>%
  filter(YEAR=="2012") %>% 
  pull(SIZE)

ivee_12

ivee_17<-IVEE_12_17 %>%
  filter(YEAR=="2017") %>% 
  pull(SIZE)

ivee_17


ivee_unpaired_t<-t.test(ivee_12, ivee_17, var.equal = TRUE)
ivee_unpaired_t  #p=0.0599; retain null

#########################################################################################

napl_12<-NAPL_12_17 %>%
  filter(YEAR=="2012") %>% 
  pull(SIZE)

napl_12

napl_17<-NAPL_12_17 %>%
  filter(YEAR=="2017") %>% 
  pull(SIZE)

napl_17


napl_unpaired_t<-t.test(napl_12, napl_17, var.equal = TRUE)
napl_unpaired_t   #p=0.5002; retain null

#########################################################################################

aque_12<-AQUE_12_17 %>%
  filter(YEAR=="2012") %>% 
  pull(SIZE)

aque_12

aque_17<-AQUE_12_17 %>%
  filter(YEAR=="2017") %>% 
  pull(SIZE)

aque_17


aque_unpaired_t<-t.test(aque_12, aque_17, var.equal = TRUE)
aque_unpaired_t   #p=0.2097; retain null

#########################################################################################

carp_12<-CARP_12_17 %>%
  filter(YEAR=="2012") %>% 
  pull(SIZE)

carp_12

carp_17<-CARP_12_17 %>%
  filter(YEAR=="2017") %>% 
  pull(SIZE)

carp_17


carp_unpaired_t<-t.test(carp_12, carp_17, var.equal = TRUE)
carp_unpaired_t   #p=0.1819; retain null

#########################################################################################

mohk_12<-MOHK_12_17 %>%
  filter(YEAR=="2012") %>% 
  pull(SIZE)

mohk_12

mohk_17<-MOHK_12_17 %>%
  filter(YEAR=="2017") %>% 
  pull(SIZE)

mohk_17


mohk_unpaired_t<-t.test(mohk_12, mohk_17, var.equal = TRUE)
mohk_unpaired_t #p-value<0.001; reject null

library(effsize)

effect_size5<-cohen.d(mohk_12, mohk_17)
effect_size5  #d=0.541 (medium)

```



```{r}
#4. 

#Will make table for # of lobsters at each site that are longer than 82.6 mm. Then I will do a chi-square test on this table.

lobster_83_up<-lobster_tidy %>% 
  filter(YEAR=="2017") %>% 
  mutate(
    size=ifelse(
      SIZE>=83,"above_83", "below_83")
  )
  

lobster_83_up

table_83_up<-lobster_83_up %>% 
  count(SITE,size) %>% 
  spread(size, n) %>% 
  select(-SITE)

rownames(table_83_up)<-c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")

table_83_up

######################################################################################
#Proportions table made

above_83_prop<-prop.table(as.matrix(table_83_up), 1)
above_83_prop

######################################################################################
#Performing chi-square

above_83_x2<-chisq.test(table_83_up)
above_83_x2  #p-value < 0.001, 0.0009864 to be exact

```

```{r}

final_prop_table<-lobster_tidy %>% 
  filter(YEAR=="2017") %>% 
  mutate(
    size=ifelse(
      SIZE>=83,"above_83", "below_83")
  ) %>% 
  group_by(SITE) %>% 
  summarize(
    total_lobsters_sampled=n(SIZE),
    legal_size_lobsters=n())

final_prop_table

```

```{r}

final_prop_table2<-lobster_tidy %>% 
  filter(YEAR=="2017") %>% 
  mutate(
    size=ifelse(
      SIZE>=83,"above_83", "below_83")
  ) %>% count(SITE,size,SIZE) %>% 
  spread(size, n)

final_prop_table2

```

